enum ApiSuccess {
  CANDIDATE_DELETED = "CANDIDATE_DELETED",
  CANDIDATE_UPDATED = "CANDIDATE_UPDATED",
  CANDIDATE_REGISTERED = "CANDIDATE_REGISTERED",
  VOTE_REGISTERED = "VOTE_REGISTERED",
}

export default ApiSuccess;
